Revert "sched/fair: Fix calc_cfs_shares() fixed point arithmetics width confusion" Reason: undefined reference to `calc_tg_weight' This reverts commit d9876b8eba8920fbd7f2d343b620405a88f9913f.